spring.application.name=auth_server
server.port=8080
ms.auth.jwt.issuer=http://localhost:8080
ms.auth.jwt.expiration-seconds=3600
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:Ov23lib2ztrqPoxNZEe7}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:3579dabed9fd26cfc895f58e6b1d40f3b81cb404}
spring.security.oauth2.client.registration.github.scope=read:user,user:email
eureka.client.service-url.defaultZone=http://eureka:eureka2026@localhost:8761/eureka/
