# Nombre logico de la aplicacion
spring.application.name=config-server

# Puerto centralizado donde escuchara peticiones este Config Server
server.port=8888

# Perfil nativo para buscar las configuraciones en el sistema de archivos local
spring.profiles.active=native

# Carpeta local que almacena los archivos .properties de cada microservicio del banco
spring.cloud.config.server.native.search-locations=file:./config-repo

# Credenciales de acceso para que los microservicios clientes puedan autenticarse
spring.security.user.name=admin
spring.security.user.password=gato
